project:
  type: website
  output-dir: docs

website:
  title: "TFG / TFM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: propuestas.qmd
        text: Propuestas
      - href: defendidos.qmd
        text: Trabajos defendidos
      - href: about.qmd
        text: Sobre nosotros


format:
  html:
    theme: cosmo
    css: styles.css  # si tienes tu tailwind procesado
    toc: true

editor: visual

